services:
  orchestrator:
    build:
      context: ./orchestrator
      args:
        PROJECT_VERSION: ${PROJECT_VERSION}
    ports:
      - "8000:8000"
    depends_on:
      - llm_interface
      - graph_service
      - rules_policy_engine
      - neural_net_service
    environment:
      - MONGODB_URI=mongodb://root@mongodb:27017/?authSource=admin
      - MONGODB_DB_NAME=fraud_detection
  llm_interface:
    build:
      context: ./llm_interface
      args:
        PROJECT_VERSION: ${PROJECT_VERSION}
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root@mongodb:27017/?authSource=admin
      - MONGODB_DB_NAME=fraud_detection
  graph_service:
    build:
      context: ./graph_service
      args:
        PROJECT_VERSION: ${PROJECT_VERSION}
    ports:
      - "8002:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root@mongodb:27017/?authSource=admin
      - MONGODB_DB_NAME=fraud_detection
  rules_policy_engine:
    build:
      context: ./rules_policy_engine
      args:
        PROJECT_VERSION: ${PROJECT_VERSION}
    ports:
      - "8003:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root@mongodb:27017/?authSource=admin
      - MONGODB_DB_NAME=fraud_detection
  neural_net_service:
    build:
      context: ./neural_net_service
      args:
        PROJECT_VERSION: ${PROJECT_VERSION}
    ports:
      - "8004:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root@mongodb:27017/?authSource=admin
      - MONGODB_DB_NAME=fraud_detection
  dashboard:
    build:
      context: ./dashboard
      args:
        PROJECT_VERSION: ${PROJECT_VERSION}
    ports:
      - "8005:8501"
    depends_on:
      - orchestrator
    environment:
      - MONGODB_URI=mongodb://root@mongodb:27017/?authSource=admin
      - MONGODB_DB_NAME=fraud_detection
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD:
    command: >
      bash -c "
      mongosh --host mongodb --port 27017 -u root --authenticationDatabase admin --eval '
        db = db.getSiblingDB(\"fraud_detection\");
        db.createUser({
          user: \"fraud_user\",
          pwd: \"secure_password\",
          roles: [ { role: \"readWrite\", db: \"fraud_detection\" } ]
        });' &&
      python /data_generator.py
      "
