version: "3.9"
services:
  app:
    build:
      context: .
      args:
        PROJECT_VERSION: 0.1.0
        COMMON_VERSION: 0.1.0
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/fraude_ai
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: